-- FractionalStay Complete Database Schema Migration
-- Generated: 2025-11-24T15:12:34.215Z
-- Description: Complete schema extracted from actual database
-- 
-- This file was auto-generated by extracting the actual schema from the database.
-- It represents the CURRENT state of your database.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- USERS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id UUID DEFAULT uuid_generate_v4(),
    wallet_address TEXT NOT NULL,
    role TEXT NOT NULL,
    kyc_status TEXT NOT NULL DEFAULT 'APPROVED',
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    business_name TEXT,
    profile_image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TEXT,
    proof_hash TEXT,
    proof_tx_hash TEXT,
    proof_provider TEXT,
    sbt_token_id INTEGER,
    sbt_metadata_cid TEXT,
    verified_at TIMESTAMPTZ,
    CONSTRAINT users_wallet_address_lowercase CHECK (wallet_address = LOWER(wallet_address))
);

CREATE INDEX IF NOT EXISTS idx_users_wallet_address ON public.users(wallet_address);
CREATE INDEX IF NOT EXISTS idx_users_kyc_status ON public.users(kyc_status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users(created_at);
CREATE INDEX IF NOT EXISTS idx_users_sbt_token_id ON public.users(sbt_token_id);
ALTER TABLE public.users ADD CONSTRAINT fk_users_wallet_address FOREIGN KEY (wallet_address) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT fk_users_sbt_token_id FOREIGN KEY (sbt_token_id) REFERENCES public.sbt(id) ON DELETE CASCADE;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- KYC_DOCUMENTS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.kyc_documents (
    id UUID DEFAULT uuid_generate_v4(),
    user_wallet TEXT NOT NULL,
    document_type TEXT NOT NULL,
    document_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'APPROVED',
    rejection_reason TEXT,
    submitted_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    reviewed_by TEXT,
    wallet_address TEXT NOT NULL,
    full_name TEXT NOT NULL,
    date_of_birth TIMESTAMPTZ,
    nationality TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT,
    id_type TEXT NOT NULL,
    id_number TEXT NOT NULL,
    address_proof_type TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    zk_proof_hash TEXT,
    zk_proof_tx_hash TEXT,
    sbt_token_id INTEGER NOT NULL,
    sbt_mint_tx_hash TEXT NOT NULL,
    sbt_metadata_cid TEXT NOT NULL,
    CONSTRAINT kyc_documents_user_wallet_lowercase CHECK (user_wallet = LOWER(user_wallet)),
    CONSTRAINT kyc_documents_wallet_address_lowercase CHECK (wallet_address = LOWER(wallet_address)),
    CONSTRAINT kyc_documents_address_lowercase CHECK (address = LOWER(address)),
    CONSTRAINT kyc_documents_address_proof_type_lowercase CHECK (address_proof_type = LOWER(address_proof_type))
);

CREATE INDEX IF NOT EXISTS idx_kyc_documents_user_wallet ON public.kyc_documents(user_wallet);
CREATE INDEX IF NOT EXISTS idx_kyc_documents_status ON public.kyc_documents(status);
CREATE INDEX IF NOT EXISTS idx_kyc_documents_wallet_address ON public.kyc_documents(wallet_address);
CREATE INDEX IF NOT EXISTS idx_kyc_documents_sbt_token_id ON public.kyc_documents(sbt_token_id);
ALTER TABLE public.kyc_documents ADD CONSTRAINT fk_kyc_documents_user_wallet FOREIGN KEY (user_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.kyc_documents ADD CONSTRAINT fk_kyc_documents_wallet_address FOREIGN KEY (wallet_address) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.kyc_documents ADD CONSTRAINT fk_kyc_documents_sbt_token_id FOREIGN KEY (sbt_token_id) REFERENCES public.sbt(id) ON DELETE CASCADE;

ALTER TABLE public.kyc_documents ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PROPERTIES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.properties (
    id UUID DEFAULT uuid_generate_v4(),
    token_id INTEGER NOT NULL,
    seller_wallet TEXT NOT NULL,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zipcode TEXT NOT NULL,
    description TEXT NOT NULL,
    property_type TEXT NOT NULL,
    total_shares INTEGER NOT NULL,
    price_per_share INTEGER NOT NULL,
    images TEXT[] NOT NULL,
    amenities TEXT[] NOT NULL,
    metadata_uri TEXT NOT NULL,
    listing_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT properties_seller_wallet_lowercase CHECK (seller_wallet = LOWER(seller_wallet)),
    CONSTRAINT properties_address_lowercase CHECK (address = LOWER(address))
);

CREATE INDEX IF NOT EXISTS idx_properties_token_id ON public.properties(token_id);
CREATE INDEX IF NOT EXISTS idx_properties_seller_wallet ON public.properties(seller_wallet);
CREATE INDEX IF NOT EXISTS idx_properties_status ON public.properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_created_at ON public.properties(created_at);
ALTER TABLE public.properties ADD CONSTRAINT fk_properties_token_id FOREIGN KEY (token_id) REFERENCES public.token(id) ON DELETE CASCADE;
ALTER TABLE public.properties ADD CONSTRAINT fk_properties_seller_wallet FOREIGN KEY (seller_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- TRANSACTIONS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.transactions (
    id UUID DEFAULT uuid_generate_v4(),
    tx_hash TEXT NOT NULL,
    type TEXT NOT NULL,
    from_wallet TEXT NOT NULL,
    to_wallet TEXT NOT NULL,
    token_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    price DECIMAL(20, 6) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    block_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'SUCCESS',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT transactions_from_wallet_lowercase CHECK (from_wallet = LOWER(from_wallet)),
    CONSTRAINT transactions_to_wallet_lowercase CHECK (to_wallet = LOWER(to_wallet))
);

CREATE INDEX IF NOT EXISTS idx_transactions_from_wallet ON public.transactions(from_wallet);
CREATE INDEX IF NOT EXISTS idx_transactions_to_wallet ON public.transactions(to_wallet);
CREATE INDEX IF NOT EXISTS idx_transactions_token_id ON public.transactions(token_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions(created_at);
ALTER TABLE public.transactions ADD CONSTRAINT fk_transactions_from_wallet FOREIGN KEY (from_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.transactions ADD CONSTRAINT fk_transactions_to_wallet FOREIGN KEY (to_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.transactions ADD CONSTRAINT fk_transactions_token_id FOREIGN KEY (token_id) REFERENCES public.token(id) ON DELETE CASCADE;

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- USER_PORTFOLIOS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_portfolios (
    id UUID DEFAULT uuid_generate_v4(),
    user_wallet TEXT NOT NULL,
    token_id INTEGER NOT NULL,
    property_name TEXT NOT NULL,
    shares_owned INTEGER NOT NULL,
    total_invested INTEGER NOT NULL,
    total_rewards_claimed INTEGER NOT NULL,
    last_updated TIMESTAMPTZ NOT NULL,
    CONSTRAINT user_portfolios_user_wallet_lowercase CHECK (user_wallet = LOWER(user_wallet))
);

CREATE INDEX IF NOT EXISTS idx_user_portfolios_user_wallet ON public.user_portfolios(user_wallet);
CREATE INDEX IF NOT EXISTS idx_user_portfolios_token_id ON public.user_portfolios(token_id);
ALTER TABLE public.user_portfolios ADD CONSTRAINT fk_user_portfolios_user_wallet FOREIGN KEY (user_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.user_portfolios ADD CONSTRAINT fk_user_portfolios_token_id FOREIGN KEY (token_id) REFERENCES public.token(id) ON DELETE CASCADE;

ALTER TABLE public.user_portfolios ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- MARKETPLACE_LISTINGS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.marketplace_listings (
    id UUID DEFAULT uuid_generate_v4(),
    listing_id INTEGER NOT NULL,
    seller_wallet TEXT NOT NULL,
    token_id INTEGER NOT NULL,
    property_name TEXT NOT NULL,
    shares_amount INTEGER NOT NULL,
    price_per_share INTEGER NOT NULL,
    total_price INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT marketplace_listings_seller_wallet_lowercase CHECK (seller_wallet = LOWER(seller_wallet))
);

CREATE INDEX IF NOT EXISTS idx_marketplace_listings_listing_id ON public.marketplace_listings(listing_id);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_seller_wallet ON public.marketplace_listings(seller_wallet);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_token_id ON public.marketplace_listings(token_id);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_status ON public.marketplace_listings(status);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_created_at ON public.marketplace_listings(created_at);
ALTER TABLE public.marketplace_listings ADD CONSTRAINT fk_marketplace_listings_listing_id FOREIGN KEY (listing_id) REFERENCES public.listing(id) ON DELETE CASCADE;
ALTER TABLE public.marketplace_listings ADD CONSTRAINT fk_marketplace_listings_seller_wallet FOREIGN KEY (seller_wallet) REFERENCES public.users(wallet_address) ON DELETE CASCADE;
ALTER TABLE public.marketplace_listings ADD CONSTRAINT fk_marketplace_listings_token_id FOREIGN KEY (token_id) REFERENCES public.token(id) ON DELETE CASCADE;

ALTER TABLE public.marketplace_listings ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- WARD_BOY_MAPPINGS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.ward_boy_mappings (
    id UUID DEFAULT uuid_generate_v4(),
    property_id INTEGER NOT NULL,
    ward_boy_address TEXT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL,
    assigned_by TEXT,
    is_active BOOLEAN NOT NULL,
    removed_at TIMESTAMPTZ,
    removed_by TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ward_boy_mappings_ward_boy_address_lowercase CHECK (ward_boy_address = LOWER(ward_boy_address))
);

CREATE INDEX IF NOT EXISTS idx_ward_boy_mappings_property_id ON public.ward_boy_mappings(property_id);
ALTER TABLE public.ward_boy_mappings ADD CONSTRAINT fk_ward_boy_mappings_property_id FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;

ALTER TABLE public.ward_boy_mappings ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RENT_DEPOSITS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.rent_deposits (
    id UUID DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT,
    property_id INTEGER,
    property_name TEXT,
    ward_boy_address TEXT,
    deposit_month TEXT,
    gross_rent TEXT,
    repairs TEXT,
    utilities TEXT,
    cleaning TEXT,
    other_expenses TEXT,
    total_miscellaneous TEXT,
    net_amount TEXT,
    notes TEXT,
    bills_metadata JSONB,
    summary_ipfs_hash TEXT,
    deposit_tx_hash TEXT,
    payout_tx_hash TEXT,
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,
    CONSTRAINT rent_deposits_ward_boy_address_lowercase CHECK (ward_boy_address = LOWER(ward_boy_address))
);

CREATE INDEX IF NOT EXISTS idx_rent_deposits_created_at ON public.rent_deposits(created_at);
CREATE INDEX IF NOT EXISTS idx_rent_deposits_status ON public.rent_deposits(status);
CREATE INDEX IF NOT EXISTS idx_rent_deposits_property_id ON public.rent_deposits(property_id);
ALTER TABLE public.rent_deposits ADD CONSTRAINT fk_rent_deposits_property_id FOREIGN KEY (property_id) REFERENCES public.property(id) ON DELETE CASCADE;

ALTER TABLE public.rent_deposits ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- INDEXER_STATE TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.indexer_state (
    id UUID DEFAULT uuid_generate_v4(),
    contract_address TEXT NOT NULL,
    last_processed_block INTEGER NOT NULL,
    last_block_hash TEXT NOT NULL,
    last_checkpoint_block INTEGER NOT NULL,
    last_checkpoint_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT indexer_state_contract_address_lowercase CHECK (contract_address = LOWER(contract_address))
);

CREATE INDEX IF NOT EXISTS idx_indexer_state_created_at ON public.indexer_state(created_at);

ALTER TABLE public.indexer_state ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- BLOCKCHAIN_EVENTS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.blockchain_events (
    id UUID DEFAULT uuid_generate_v4(),
    event_name TEXT,
    contract_address TEXT,
    block_number BIGINT,
    block_hash TEXT,
    transaction_hash TEXT,
    log_index INTEGER,
    args JSONB,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT blockchain_events_contract_address_lowercase CHECK (contract_address = LOWER(contract_address))
);


ALTER TABLE public.blockchain_events ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE public.users IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.kyc_documents IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.properties IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.transactions IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.user_portfolios IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.marketplace_listings IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.ward_boy_mappings IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.rent_deposits IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.indexer_state IS 'Auto-generated from actual database schema';
COMMENT ON TABLE public.blockchain_events IS 'Auto-generated from actual database schema';

-- ============================================================================
-- COMPLETION MESSAGE
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE '✅ FractionalStay Database Schema Migration Complete!';
    RAISE NOTICE '📊 Tables: 10 tables';
    RAISE NOTICE '🎯 Schema extracted from actual database on 2025-11-24T15:12:34.216Z';
END $$;
